config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # impossible to push to heroku without a root !
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create] do
      #get 'dose', to: 'cocktails#dose', as: :dose
    end
    resources :reviews, only: [:new, :create] do
    end
  end
  # resources :ingredients
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
    has_many :reviews, dependent: :destroy

    validates :name, presence: true, uniqueness: :true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end
 

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses
    has_many :cocktails, through: :doses

    validates :name, presence: true, uniqueness: :true
end
 

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: :true
  validates :stars, presence: :true, inclusion: { in: 0..5, allow_nil: false}
  belongs_to :cocktail

  def blank_stars
    5 - stars.to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    # search bar
    if params[:query].present?
      @query = params[:query].capitalize
      @cocktails = Cocktail.where("name LIKE ?", "%#{@query}%")
    else
      @cocktails = Cocktail.all.order(:name)
    end
end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
    # @dose = Dose.new
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    raise
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :description)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :show]
  # before_action :set_dose
  # before_action :set_ingredient
  # before_action :set_dose, only: [:destroy]

  def new
      # build : comme un new mais le cocktail ID est pré-remplis
      @dose = @cocktail.doses.build
  end
  def create
    @dose = Dose.new(dose_params)
    # raise
    @dose.cocktail = @cocktail
    @dose.ingredient = Ingredient.find(params["dose"]["ingredient"]) unless params["dose"]["ingredient"].blank?
    if @dose.save
      redirect_to cocktail_url(@cocktail), notice: 'cocktail was successfully destroyed.'
    else
     render :new
     # render 'cocktails/show' # to have verifications on the same page
    end
  end

  def destroy
    # @dose = Ingredient.find(params[:ingredient_id])
    # @dose.cocktail = @cocktail
    # @dose.ingredient = Ingredient.find(params["dose"]["ingredient"])
    @dose = Dose.find(params[:id])
    # @dose.destroy
    if @dose.destroy
      redirect_to cocktail_url(@dose.cocktail), notice: 'Ingredient was successfully destroyed.'
    else
     render :new
     # render 'cocktails/show' # to have verifications on the same page
    end
  end

  private
  def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
  end
  # si on autorise par 'ingredient_id' dans les strong params
  # alors impossible de supprimer car il ne peut pas récuperer 
  # l'ingredient_id !!!!!!!!!!
  def dose_params
      params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [:new, :create, :show]

  def new
      # build : comme un new mais le cocktail ID est pré-remplis
      @review = @cocktail.reviews.build
  end
  def create
      @review = Review.new(review_params)
      @review.cocktail = @cocktail
      # raise
      if @review.save
        redirect_to cocktail_url(@cocktail), notice: 'cocktail was successfully destroyed.'
      else
       render :new
       # render 'cocktails/show' # to have verifications on the same page
      end
  end
  def destroy
    # NB : ip notice n'est pas coder sur le form
    @review = Review.find(params[:id])
    # raise
    if @review.destroy
        # redirect_to cocktails_url, notice: 'Review was successfully destroyed.'
        redirect_to cocktail_url(@review.cocktail), notice: 'Review was successfully destroyed.'
      else
       render :new
       # render 'cocktails/show' # to have verifications on the same page
    end
  end

  private
  def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
  end
  def review_params
      params.require(:review).permit(:content, :stars, :cocktail_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <% if cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
        <% cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.input :photo %>
    <%=  f.input :photo_cache, as: :hidden %>
  </div>
  <%# Using style to custom the upload picture file %>
  <%# <div class="form-group fileUpload btn btn-primary upload-height">
    <%= f.input :photo, input_html: { class: 'upload' }, label: 'Choose a Picture !' %>
    <%#=  f.input :photo_cache, as: :hidden %>
  <%# </div> %>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, size: "50" %>
  </div>
  <div class="form-group">
    <%#= f.input :doses %>
  </div>
  <div class="form-group">
    <%#= f.association :ingredients %>
  </div>
  <div class="form-group">
  <%#= f.association :doses %>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', cocktails_path, class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="cocktail-form">
        <h1>Edit cocktail</h1>
        <div class="mt-3">
            <%= render 'form', cocktail: @cocktail %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="home-banner">
  <h1 class="animation slideDown bold-txt">Let's make awsome Cocktail ! Find your favorite Cocktail among our many recipes or make your own .. </h1>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Cocktails</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @cocktails.count %> Cocktails out of our <%= Cocktail.count %> on our website.</p>
      <% else %>
        <p>All <%= Cocktail.count %> cocktails.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-4">
        <div class="cocktail-card">
        <!--  <div class="cocktail-card-image" style="background-image: url('<%= cocktail.photo %>')">  -->
        <div class="cocktail-card-image"><%= cl_image_tag cocktail.photo, height: 180, width: 350, crop: :fill %></div>
          <div class="cocktail-card-content">
            <div class="cocktail-card-title">
              <h4><%= cocktail.name %></h4>
            </div>

          </div>
          <div class="cocktail-card-actions">
            <%= link_to 'More info', cocktail_path(cocktail) %>
            <%= link_to 'Edit', edit_cocktail_path(cocktail), class: 'ml-3 text-warning' %>
            <%= link_to "Remove", cocktail_path(cocktail),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="cocktail-form">
        <h1>New Cocktail</h1>
        <div class="mt-3">
            <%= render 'form', cocktail: @cocktail %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="map" style=""></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="cocktail-show-card-one">
        <h1><%= @cocktail.name %></h1>
        <div class="cocktail-card-image"><%= cl_image_tag @cocktail.photo, height: 180, width: 350, crop: :fill %></div>
      </div>
      <div class="cocktail-show-card">
        <h3>A bit more about this cocktail...</h3>
        <p><%= @cocktail.description %></p>
        <h3>Ingredients</h3>
        <ul class="list-unstyled">
          <% @cocktail.doses.each do |dose| %>
          <li>
            <p style="color: grey"><strong>Ingredient : </strong><%= dose.ingredient.name %> - <%= dose.description %>&nbsp;&nbsp;
            <%= link_to dose_path(dose), method: :delete, data: { confirm: "Do you really want to delete #{dose.ingredient.name}?" } do %>
            <i class="fas fa-trash-alt" style="color: grey" aria-hidden="true"></i><% end %></p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-4">
      <div class="cocktail-show-card">
        <h5>Make this Cocktail !</h5>
        <p>Follow the recipe or make your own !</p>
      </div>

      <div class="cocktail-show-card">
        <h3>Manage Ingredients</h3>
        <div class="#">
          <div>
            <span>You can add or delete ingredients to better fit your taste</span>
          </div>
          <br>
          <div class="#">
            <%#= link_to 'Add Dose', new_cocktail_ingredient_path(@cocktail), class: "btn btn-outline-primary my-2 my-sm-0 ml-2" %>
            <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary", id: "ingredient-add-button"%>
            <%= link_to "Go Back", cocktails_path, class: "btn btn-warning" %>
          </div>
        </div>
      </div>

    </div>

    <div class="col-8">
      <div class="cocktail-show-card">
        <h3>Reviews ...</h3>
            <ul>
              <% @cocktail.reviews.each do |review| %>
                <li style="color: grey"><strong>Review : </strong><%= review.content %>&nbsp;
                  <strong>Rating : </strong>
                  <% review.stars.times do  %>
                    <i class="fas fa-star" style="color: #FFC700" aria-hidden="true"></i>
                  <% end %>
                  <% review.blank_stars.times do %>
                    <i class="far fa-star" aria-hidden="true"></i>
                  <% end %>
                  <%#= review.stars %>&nbsp;&nbsp;
                <%= link_to review_path(review), method: :delete, data: { confirm: "Do you really want to delete this Review ?" } do %>
                <i class="fas fa-trash-alt" style="color: grey" aria-hidden="true"></i><% end %></p>
                </li>
              <% end %>
            </ul>
            <%#= link_to 'Add Dose', new_cocktail_ingredient_path(@cocktail), class: "btn btn-outline-primary my-2 my-sm-0 ml-2" %>
            <%= link_to "Add Review",  new_cocktail_review_path(@cocktail), class: "btn btn-secondary", id: "review-add-button"%>
      </div>
    </div>
    
  </div>
</div>

app/views/doses/new.html.erb
<div class="container padded">
  <h3 class="text-center">Add an ingredient</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= simple_form_for([@cocktail, @dose]) do |form| %>
        <% if @dose.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@dose.errors.count, "error") %> prohibited this dose from being saved:</h2>

            <ul>
              <% @dose.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <p><strong><%= form.label :description %></strong><br>
          <%= form.text_field :description, size: 30 %></p>
        </div>

        <div class="form-group">
          <%#= form.input :description %>
          <%#= form.association :cocktail %>
          <%= form.input :ingredient, collection: Ingredient.all.order(:name), selected: "lemon"  %>
          <%#= form.association :ingredients %>
          <%#= f.input :ingredient, collection: Ingredient.order(:name),  prompt: "Pick one from list" %>
          <%#= f.association :ingredients %>
        </div>

        <div>
          <%= form.submit 'Create', :class => 'btn btn-warning' %>
        </div>
      <% end %>
      <br>
    </div>
  </div>
</div>

<%#= simple_form_for [@cocktail, @dose] do |f| %>
        <%#= f.input :description %>
        <%#= f.input :ingredient, collection: Ingredient.all, selected: "lemon"  %>
        <%#= f.submit "Submit", class: "btn btn-danger" %>
<%# end %>

app/views/ingredients/_form.html.erb
<%= simple_form_for(ingredient) do |f| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', cocktails_path, class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/ingredients/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="ingredient-form">
        <h1>New ingredient</h1>
        <div class="mt-3">
            <%= render 'form', ingredient: @ingredient %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<h1> Other cocktails with <%= @ingredient.name %> </h1>

<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li> <%= cocktail.name %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>FrontEndDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="cocktail-form">
        <h1>New Review</h1>
        <div class="mt-3">
            <%= simple_form_for([@cocktail, @review]) do |form| %>
                <% if @review.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

                    <ul>
                    <% @review.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
                <% end %>

                <div class="form-group">
                <p><strong><%= form.label :content %></strong><br>
                <%= form.text_area :content, size: "50" %></p>
                </div>

                <div class="form-group">
                  <%= form.label :stars %>
                  <%= form.number_field :stars %>
                </div>

                <div>
                <%= form.submit 'Create', :class => 'btn btn-warning' %>
                <%= link_to 'Cancel', cocktails_path, class: 'btn btn-danger ml-2' %>
                </div>
            <% end %>
            <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-light navbar-lewagon">
        <a class="navbar-brand" href="/cocktails"><%#= image_tag "logococktail.png" %></a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex justify-content-end ml-auto flex">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
              <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/cocktails/new">Add Cocktail</a>
          </div>
        </div>
  </nav>
</div>